// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type User struct {
	ID           string
	Username     string
	PasswordHash string
	ImgUrl       string
	CreatedAt    int64
}
